---
- name: Deploy honeypots
  hosts: localhost
  roles:
    - deployment

- name: Configure nodes
  hosts: added_hosts
  remote_user: "{{ ansible_ssh_user }}"
  become_user: root
  become_method: su
  vars:
    ansible_sudo_pass: "{{ vmware_vm_ssh_pass | default(omit) }}"
    ansible_become_pass: "{{ vmware_vm_ssh_pass | default(omit) }}"
    ansible_become_password: "{{ vmware_vm_ssh_pass | default(omit) }}"

  tasks:

    # Run in the honeypot VM
    - block:
      - name: Create a directory if it does not exist
        ansible.builtin.file:
          path: /tmp/{{ honeypot_name }}
          state: directory
          mode: '0755'

      - name: Copy Docker Compose files
        template:
          src: "{{ compose_file }}"
          dest: "/tmp/docker-compose.yml"

      - name: Start Docker service
        command: "systemctl start docker"

      - name: Start Docker Compose
        command: "docker compose -f /tmp/docker-compose.yml up -d"
        register: output
        ignore_errors: true
      vars:
        ansible_become_pass: "{{ vmware_vm_ssh_pass | default(omit) }}"
        ansible_become_password: "{{ vmware_vm_ssh_pass | default(omit) }}"
        ansible_sudo_pass: "{{ vmware_vm_ssh_pass | default(omit) }}"
      become: true
      when: compose_file is defined and compose_file and compose_file != ""
