# Generated by Django 4.1.1 on 2022-09-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HoneypotHasAttacker",
            new_name="HoneypotAttack",
        ),
    ]
