# Generated by Django 4.0.6 on 2022-08-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_delete_honeypotasdasd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attackdump",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
