---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: honeypot-deployment
  labels:
    app: honeypot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: honeypot
  template:
    metadata:
      labels:
        app: honeypot
    spec:
      nodeName: kube-worker
      containers:
      - name: honeypot
        image: quay.io/mnecas0/honeypot:latest
        ports:
        - containerPort: 80
        env:
        - name: SERVER
          value: "honeypot-server-service:8000"
        - name: HONEYPOT_NAME
          value: "Test"
        - name: HONEYPOT_TYPE
          value: "general"
        - name: ID
          value: "10"
        - name: DEBUG
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: honeypot-service
spec:
  selector:
    app: honeypot
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
  externalIPs:
    - 192.168.122.14
