name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Web server tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PyPi deps
        run: pip3 install -r requirements.txt

      - name: Prepare Django database
        run: |
          python3 manage.py makemigrations
          python3 manage.py migrate

      - name: Build the project
        run: python3 manage.py test
